# Generated by Django 5.0.6 on 2024-06-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_rename_bid_bids_auctions_alter_bids_auction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctions',
            name='end_time',
        ),
        migrations.AddField(
            model_name='auctions',
            name='duration',
            field=models.IntegerField(default=24),
        ),
    ]
