# Generated by Django 5.0.6 on 2024-06-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_remove_auctions_end_time_auctions_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='duration',
            field=models.IntegerField(default=86400),
        ),
    ]
