# Generated by Django 5.0.3 on 2024-05-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='byear',
            field=models.IntegerField(default=1980),
        ),
    ]
