# Generated by Django 5.0.3 on 2024-05-17 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_post_byear'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=10)),
                ('user_city', models.CharField(max_length=10)),
                ('user_school', models.BooleanField(default=False)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_message', models.TextField()),
            ],
        ),
    ]
